server.port: 8000

storage:
  raw: '/home/hack/raw'
  udpipe: '/home/hack/udpipe'

spring:
  datasource:
    url: 'jdbc:h2:mem:testdb'
  h2.console:
    enabled: true
    path: /h2
    settings.web-allow-others: true
  jpa:
    show-sql: false
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

command-executor:
  working-dir: '/home/hack/'
  timeout: 10
